# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HcgBXMYtgAef__gKISDbmJ6wxf9jNU3S
"""

import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/tested.csv')

age_series = df['Age']
fare_series = df['Fare']
survived_series = df['Survived']

print(df.head())
print(df.info())
print(df.describe())

print(df.isnull().sum())

df['Age'] = df['Age'].fillna(df['Age'].mean())

df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

df['Fare'] = df['Fare'].fillna(df['Fare'].median())

top_ten = df.iloc[0:10]

name_survival = df.loc[:, ['Name', 'Survived']]

df.rename(columns={'Sex': 'Gender'}, inplace=True)

pivot_analysis = df.pivot_table(index='Pclass', columns='Gender', values='Survived', aggfunc='mean')
print(pivot_analysis)

filtered_data = df[(df['Age'] > 30) & (df['Fare'] > 50) & (df['Survived'] == 1)]


sorted_by_fare = df.sort_values(by='Fare', ascending=False)

print(df.groupby('Gender')['Survived'].mean())

print(df.groupby('Pclass')['Age'].mean())

print(df.groupby('Embarked')['Survived'].sum())

class_labels = pd.DataFrame({
    'Pclass': [1, 2, 3],
    'Class_Type': ['First Class', 'Second Class', 'Third Class']
})

df = pd.merge(df, class_labels, on='Pclass', how='left')

avg_age_survivors = df[df['Survived'] == 1]['Age'].mean()
avg_age_non_survivors = df[df['Survived'] == 0]['Age'].mean()

max_fare = df['Fare'].max()
min_fare = df['Fare'].min()

survival_pct = (df['Survived'].mean()) * 100

print(f"Survival Rate: {survival_pct:.2f}%")
print(f"Highest Fare Paid: {max_fare}")